### ISSUE TITLE
.org mode support?

### ISSUE THREAD

**Issue by githubtefo** [flathub/org.gnome.gitlab.cheywood.Iotas#6] opened 2023-02-04 19:18 UTC
Hi all!

Great project! Do you have plans to implement .org mode from the client side of Iotas? I know Nextcloud Notes doesn't support it, but at least having it in one client would be a great addition! There are a bunch of scientists using .org mode trying that Nextcloud would include it for Notes and this can be a good start.
Thanks!

**Comment by cheywood** [comment] 2023-02-06 02:20
Hi githubtefo! Thanks for getting in touch.

That's definitely an interesting idea you have there. Iotas though, as it says in the description and README etc, is by design a simple note taking app and what you're after here is definitely a quite advanced and somewhat niche feature.

So while this won't be built into Iotas please feel free to use Iotas as a base to build an org mode GTK4 app on top of, if that's useful.

I'll close this issue, but if you have any other Iotas thoughts feel free to get in touch at the [issue tracker for the project](https://gitlab.gnome.org/cheywood/iotas/-/issues) (as this issue tracker is just for the Flathub packaging).

**Closed as completed by cheywood** 2023-02-06 02:20 UTC
